source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Concierge_Example', :exclusive => true do
  pod "Concierge", :path => "../"
end

target 'Concierge_Tests', :exclusive => true do
  pod "Concierge", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
